title: "Balbino Tchoutzine"
description: "Étudiant en Génie Informatique - Passionné d'IA et de NLP"
theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: mmistakes/minimal-mistakes


header_links:
  - title: "Projets"
    url: /projects
  - title: "Engagement"
    url: /engagement
  - title: "Blog"
    url: /blog
  - title: "À propos"
    url: /about


author:
  name: "Balbino Tchoutzine"
  avatar: "/assets/images/balbino.jpg"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/zoom-BT"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/balbino-tchoutzine"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:tchoutzine@gmail.com"
